### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hb0730** [13enBi/vite-plugin-utools#1]
![image](https://user-images.githubusercontent.com/33956166/164912282-b01d0a2f-c481-46f2-8c34-1f28b2febd81.png)
![image](https://user-images.githubusercontent.com/33956166/164912298-291ba73d-a351-4e11-b24f-a1c729b4d8fa.png)
![image](https://user-images.githubusercontent.com/33956166/164912427-0cb3b80c-81b4-4a82-a586-dc0bab3d8b36.png)

**Comment by hb0730** [comment]
![image](https://user-images.githubusercontent.com/33956166/164912643-d0f0a02b-d525-4064-a4ab-71e74bc4bd89.png)

**Comment by hb0730** [comment]
config.json 还需要`logo`

**Comment by hb0730** [comment]
> config.json 还需要`logo`

`features`

**Comment by 13enBi** [comment]
已修复([PR](https://github.com/13enBi/vite-plugin-utools/pull/2))，将版本更新至`0.0.5`再试下

**Comment by hb0730** [comment]
OK
