### ISSUE TITLE
使用jschardet模块有问题

### ISSUE THREAD

**Issue by wellenChen** [13enBi/vite-plugin-utools#10]
用`const jschardet = require('jschardet');`引入模块是可以正常调用detect方法，但是这种引入方式构建后再dist目录下没有jschardet.js
[示例](https://fastly.jsdelivr.net/gh/wellenChen/tuchuang@main/images/16787551485701678755147988.png)
用`import jschardet from "jschardet";`引入调用detect方法会报错
[报错提示](https://fastly.jsdelivr.net/gh/wellenChen/tuchuang@main/images/16787551235691678755122863.png)
😅😅

**Comment by 13enBi** [comment]
没复现，给个 demo ？

**Comment by wellenChen** [comment]
> 
链接: https://pan.baidu.com/s/1_EVsMEeRplwNq-k-sQ7CEw?pwd=nfxs 提取码: nfxs 。麻烦了😀

**Comment by 13enBi** [comment]
看了下类似的 [issues](https://github.com/aadsm/jschardet/issues/68#issuecomment-888661929)，这个模块在 "use strict" 模式下会出现这个问题，vite 打包后默认是在 "use strict" 模式。解决方式也很简单，在 vite.config 中把 output.strict 设置为 false。
```typescript
export default defineConfig({
  // ...其他配置项
  build: {
    rollupOptions: {
      output: {
        strict: false,
      },
    },
  },
});
```

**Comment by xuehuangzheng123** [comment]
我在构建前使用和构建后使用，发现这个值在构建前是数组，构建后变成字符串了，请问这是什么情况
![image](https://github.com/13enBi/vite-plugin-utools/assets/127759655/6ccf55bf-e88a-463e-a0dd-8fdcfdaf04ea)
![image](https://github.com/13enBi/vite-plugin-utools/assets/127759655/e68e49a9-7754-448a-8dcf-a7652a6543ba)
