### ISSUE TITLE
版本升级导致意外行为

### ISSUE THREAD

**Issue by ZiuChen** [13enBi/vite-plugin-utools#12]
我将包版本从`v0.5.2`升级到`v0.5.3`后遇到了这样的问题：

`preload.js`与`time.js`位于同一目录下，文件内容分别如下：

```js
// preload.js
import time from './time'
export { time }
```
```js
// time.js
const path = require('path')
const worker = new Worker(path.join(__dirname, 'time.worker.js'))
function sleep() {
  worker.postMessage('sleep')
}
export default { sleep }
```

使用`v0.5.2`的vite-plugin-utools对`preload.js`打包，最终的`preload.js`产物：

```js
"use strict";
const path = require("path");
const worker = new Worker(path.join(__dirname, "time.worker.js"));
function sleep() {
  worker.postMessage("sleep");
}
const time = {
  sleep
};
window.preload = /* @__PURE__ */ Object.create(null);
window.preload["time"] = time;
```

使用`v0.5.3`的vite-plugin-utools对`preload.js`打包，最终的`preload.js`产物：

```js
"use strict";
const vendor = require("./node_modules/vendor.js");
window.preload = /* @__PURE__ */ Object.create(null);
window.preload["time"] = vendor.time;
```

可以发现：`time.js`中需要执行的代码没有被打包进最终的`preload.js`中
当产物`preload.js`被执行时不会执行之前写在`time.js`顶层的代码

检查了一下版本升级到v0.5.3后的代码变动：https://github.com/13enBi/vite-plugin-utools/commit/cc771401193576f31a83d4133c87fcfb8ca9b49c ，不太能理解其中原因

我想知道这是我代码的问题还是包的问题

**Comment by 13enBi** [comment]
time.js 打包进 node_modules/vendor.js 中了，导致产物代码中 __dirname 和 time.worker.js 相对路径前后版本有差异的问题吧
