### ISSUE TITLE
啥时候支持一下preload引入第三方库

### ISSUE THREAD

**Issue by lblblong** [13enBi/vite-plugin-utools#3]

**Comment by 13enBi** [comment]
我最近看看吧

**Comment by lblblong** [comment]
蟹蟹蟹蟹

**Comment by 13enBi** [comment]
更新到这个版本试试？[0.2.0-beta.1](https://www.npmjs.com/package/vite-plugin-utools/v/0.2.0-beta.1)

**Comment by 13enBi** [comment]
更新到这个版本试下？[0.2.1-beta.1](https://www.npmjs.com/package/vite-plugin-utools/v/0.2.1-beta.1)

**Comment by lblblong** [comment]
可以引入第三方库了，但是使用的时候报错了：
![image](https://user-images.githubusercontent.com/18625523/196040385-72e9d6a5-e1d9-4e9e-a5a6-7d2aa9528a59.png)

preload：
![image](https://user-images.githubusercontent.com/18625523/196040358-2ce1b3ba-3951-4266-a8fe-1e36f280497a.png)

**Comment by 13enBi** [comment]
再试下这个版本吧  [0.2.2-beta.2](https://www.npmjs.com/package/vite-plugin-utools/v/0.2.2-beta.2)

**Comment by lblblong** [comment]
哇，完美！
