### ISSUE TITLE
构建后保持`preload`可读性

### ISSUE THREAD

**Issue by ZiuChen** [13enBi/vite-plugin-utools#5]
上架uTools应用商店的插件需要保持preload的可读性
使用`vite-plugin-utools`将preload打包后源代码被混淆，请问是否有办法保持输出的preload文件的可读性

**Comment by 13enBi** [comment]
在试下 0.4.0 版本？ 不知道是不是你想要的效果

**Comment by ZiuChen** [comment]
> 在试下 0.4.0 版本？ 不知道是不是你想要的效果

是的，太完美了，感谢作者！

**Comment by 13enBi** [comment]
> > 在试下 0.4.0 版本？ 不知道是不是你想要的效果
> 
> 是的，太完美了，感谢作者！

不客气，欢迎提 issue
