### ISSUE TITLE
从文件夹的index导入preload脚本 打包第三方库提供最小化选项

### ISSUE THREAD

**Issue by ZiuChen** [13enBi/vite-plugin-utools#6]
插件版本`0.4.1`

使用的过程中遇到了一些小问题：

- 从其他文件导入`preload`文件夹中的`index.ts`时遇到了问题
  - 通常情况下`preload.ts`是单独的文件 但在我的项目中 `preload`文件位于文件夹中：`src/preload/index.ts`
  - 在其他文件中无法通过`import { fs } from '@/preload'`直接导入
  - 而必须进一步指定`index.ts` 通过`import { fs } from '@/preload/index.ts'`
- 打包进入`node_modules`的第三方库是否可以最小化 进一步压缩插件体积（最好是提供一个配置项 决定是否minify）

**Comment by 13enBi** [comment]
更新到`0.5.2`版本试试捏，配置项就`preload.minify`吧

**Comment by ZiuChen** [comment]
🤙🤙🤙 刚刚测试了一下，完美！
感谢作者！
