### ISSUE TITLE
有环境要求吗

### ISSUE THREAD

**Issue by evansisme** [13enBi/vite-plugin-utools#8]
**环境**
> node 16.16.0
> vite4.0.0 + vue3

空项目直接引入这个插件。但是找不到preload里面的方法。

**vite.config.js**
![image](https://user-images.githubusercontent.com/18202841/218701596-7202a133-bd25-4ce2-8796-431ab221f74f.png)

**preload.js**
![image](https://user-images.githubusercontent.com/18202841/218700100-8abe0bae-1493-414f-884a-24587d829a2a.png)

**index.js**
![image](https://user-images.githubusercontent.com/18202841/218700152-7869b93e-7513-4071-80a8-e903479ed835.png)

**报错**
![image](https://user-images.githubusercontent.com/18202841/218699943-ac2a9bc0-875f-4e45-8369-edff4d939601.png)

**Comment by 13enBi** [comment]
- 环境是满足的
- 尝试在 uTools 开发者工具中选择用项目 dist 目录下的 plugin.json 启动？

**Comment by evansisme** [comment]
> * 环境是满足的
> * 尝试在 uTools 开发者工具中选择用项目 dist 目录下的 plugin.json 启动？

好使了，谢谢。
