### ISSUE TITLE
写了个demo但是无法使用，为什么？

### ISSUE THREAD

**Issue by wellenChen** [13enBi/vite-plugin-utools#9]
我尝试写了个demo，编译后插件无法启动，是什么问题？[报错图片](https://fastly.jsdelivr.net/gh/wellenChen/tuchuang@main/images/1677459603722QQ%E6%88%AA%E5%9B%BE20230227085753.png) dome链接: https://pan.baidu.com/s/1He0zYjM6uxDNtpOiONtt7w?pwd=e3cs 提取码: e3cs

**Comment by 13enBi** [comment]
更新到 `0.5.3` 版本试试，建议把 `preload`文件放在 `src`目录下。

**Comment by wellenChen** [comment]
可了，谢谢大佬
